# Generated by Django 5.2.17 on 2026-09-23 19:04

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Описание каталога')),
            ],
            options={
                'verbose_name': 'каталог документов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='PdfDocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('page_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество страниц')),
                ('pdf_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_pages', to='wagtaildocs.document', verbose_name='PDF-документ')),
            ],
            options={
                'verbose_name': 'PDF-документ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('comment', wagtail.fields.RichTextField(verbose_name='Комментарий')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='catalog.pdfdocumentpage')),
            ],
            options={
                'verbose_name': 'комментарий к странице',
                'verbose_name_plural': 'комментарии к страницам',
                'ordering': ['page_number', 'sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('page', 'page_number'), name='unique_comment_per_pdf_page')],
            },
        ),
    ]
