# Generated by Django 5.2.17 on 2026-09-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_documentindexpage_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageComment',
        ),
    ]
